modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/dmitibrr/localhelperutils/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
logoFile="modicon.png"
description='''A handy client-side helper: instant block replacement, storage sorting and a local chest index.
Небольшой клиентский помощникъ: мгновенная замѣна блоковъ, сортировка хранилищъ и локальный указатель сундуковъ.'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="CLIENT"